version: "3"
services:
  web:
    build: ./
    environment:
      - MONGODBURI=store
    volumes:
      - ./:/home/projects/emitter/
    ports:
      - "3000:3000"
    depends_on:
      - store
  store:
    image: mongo
    ports: 
      - "27017"